server:
    port: 9000
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/RamanpreetKhattra/expense-tracker-configserver.git
                    searchPaths: MASTER